version: '3'

services:
  server:
    build: .
    ports:
      - "8211:8001"
    networks:
      - photon_trail
    depends_on:
      - db
      - sts
    environment:
      - TZ=Asia/Shanghai
    restart: always
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: photon_trail
    ports:
      - "3302:3306"
    volumes:
      - ./data/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/log:/var/log
    networks:
      - photon_trail
    restart: always
  sts:
    build: ./oss-uploader
    environment:
      OSS_ACCESS_KEY_ID: ""
      OSS_ACCESS_KEY_SECRET: ""
      OSS_STS_ROLE_ARN: ""
    networks:
      - photon_trail
networks:
  photon_trail:
    driver: bridge