app:
  addr: ':8001'
  api_prefix: '/api/v1'
  debug: true
database:
  username: root
  password: PhotonTrailB612!@#$
  host: 'db:3306'
  db_name: photon_trail
  charset: utf8
  parse_time: true
  max_idle_conns: 10
  max_open_conns: 30
jwt:
  key: "PhotonTrailB612!@#$"
  issuer: "kkkstra.cn"
  expire: 604800